# Generated by Django 5.2 on 2025-07-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='callback_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
